type: object
required:
  - type
properties:
  type:
    enum:
      # content will be script generated
    description: Used to specify the widget.

  title:
    type: string
    description: The title of the widget. If left blank it will be defined by the widget.

  title-url:
    type: string
    description: The URL to go to when clicking on the widget's title. If left blank it will be defined by the widget (if available).

  cache:
    type: string
    pattern: ^\d+[smhd]$
    description: How long to keep the fetched data in memory. The value is a string and must be a number followed by one of s, m, h, d.
    examples:
      - 1h
    errorMessage: Must be a valid time duration.

  css-class:
    type: string
    description: Set custom CSS classes for the specific widget instance.

  hide-header:
    type: boolean
    description: Hides the widget header when set to true. Not available for group widgets.
